export type Lang = 'ar' | 'en';

export const siteContent = {
  ar: {
    dir: 'rtl',
    nav: ['الرئيسية', 'من نحن', 'الخدمات', 'الأعمال', 'تواصل'],
    heroBadge: 'هاس ميديا',
    coverTitle: 'شركة دعاية وإعلان',
    coverSubtitle: 'نصنع هويتك باحتراف',
    heroText: 'حلول تسويقية متكاملة',
    ctaPrimary: 'واتساب',
    ctaSecondary: 'خدماتنا',
    aboutEyebrow: 'من نحن',
    aboutTitle: 'هاس ميديا',
    aboutText: 'شركة تسويق بالكويت',
    heroTitle: 'إبداع بلا حدود',
    servicesEyebrow: 'خدماتنا',
    servicesTitle: 'خدماتنا',
    services: [{ title: 'تصميم', text: 'تصميم احترافي' }],
    portfolioEyebrow: 'أعمالنا',
    portfolioTitle: 'أعمالنا',
    portfolio: [{ title: 'مشروع', category: 'تصميم', text: 'تفاصيل' }],
    clientsEyebrow: 'عملاؤنا',
    clientsTitle: 'عملاؤنا',
    clients: ['عميل'],
    contactEyebrow: 'تواصل',
    contactTitle: 'تواصل معنا',
    contactText: 'نحن جاهزون',
    contactPrimary: 'واتساب',
    contactSecondary: 'إيميل',
    contactThird: 'إنستغرام',
    footer: 'جميع الحقوق محفوظة',
    location: 'الكويت',
  },
  en: {
    dir: 'ltr',
    nav: ['Home', 'About', 'Services', 'Portfolio', 'Contact'],
    heroBadge: 'Has Media',
    coverTitle: 'Marketing Agency',
    coverSubtitle: 'We build brands',
    heroText: 'Full marketing solutions',
    ctaPrimary: 'WhatsApp',
    ctaSecondary: 'Services',
    aboutEyebrow: 'About',
    aboutTitle: 'Has Media',
    aboutText: 'Marketing company',
    heroTitle: 'Creative Agency',
    servicesEyebrow: 'Services',
    servicesTitle: 'Services',
    services: [{ title: 'Design', text: 'Professional' }],
    portfolioEyebrow: 'Portfolio',
    portfolioTitle: 'Work',
    portfolio: [{ title: 'Project', category: 'Design', text: 'Details' }],
    clientsEyebrow: 'Clients',
    clientsTitle: 'Clients',
    clients: ['Client'],
    contactEyebrow: 'Contact',
    contactTitle: 'Contact us',
    contactText: 'We are ready',
    contactPrimary: 'WhatsApp',
    contactSecondary: 'Email',
    contactThird: 'Instagram',
    footer: 'All rights reserved',
    location: 'Kuwait',
  },
};
